site_name: Woodpecker
repo_name: 'laszlocph/woodpecker'
repo_url: 'https://github.com/laszlocph/woodpecker'
copyright: 'Copyright &copy; 2019 Laszlo Fogas'
nav:
  - Home: index.md
  - Server setup: server-setup.md
theme:
  name: 'material'
  logo: 'images/favicon.svg'
  favicon: 'images/favicon.svg'
  palette:
    primary: 'green'
    accent: 'red'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite

extra:
  social:
    - type: globe
      link: http://woodpecker.laszlo.cloud
    - type: twitter
      link: https://twitter.com/laszlocph
